window.TRAINING_DATA = [
  {code:'G2402024',year:2024,title:'A historia, os usos e a aprendizaxe da lingua escrita',entity:'CAFI',detail:'Mellorar e compartir sempre',hours:1,topic:'Biblioteca e lingua'},
  {code:'S2431006',year:2024,title:'PFPP do IES Plurilingüe de Ames',entity:'CAFI',detail:'Radio escolar',hours:8,topic:'Radio escolar'},
  {code:'S2331002',year:2024,title:'PFPP do CEIP Plurilingüe de Pedrouzos',entity:'CAFI',detail:'A radio dos Polos Creativos',hours:3,topic:'Radio escolar'},
  {code:'S2331142',year:2024,title:'PFPP do CEIP Plurilingüe Santa María do Castro',entity:'CAFI',detail:'Dinamización da radio na biblioteca escolar',hours:9,topic:'Radio escolar'},
  {code:'S2331064',year:2024,title:'PFPP do CEP Plurilingüe de Ventín',entity:'CAFI',detail:'A radio escolar como proxecto de centro aberto á comunidade',hours:3,topic:'Radio escolar'},
  {code:'S2302019',year:2024,title:'Uso didáctico da radio escolar',entity:'CAFI',detail:'Uso didáctico da radio escolar',hours:8,topic:'Radio escolar'},
  {code:'V2231144',year:2023,title:'PFPP do CEIP Plurilingüe de Belesar',entity:'Vigo',detail:'Radio escolar',hours:4,topic:'Radio escolar'},
  {code:'V2131115',year:2022,title:'PFPP do CEIP Plurilingüe de Belesar',entity:'Vigo',detail:'Dinamización da biblioteca escolar e formación de persoas usuarias',hours:3,topic:'Biblioteca e lingua'},
  {code:'G2001047',year:2020,title:'Identidade dixital. Elaboración de materiais',entity:'CAFI',detail:'Identidade dixital: elaboración de materiais',hours:25,topic:'Identidade dixital'},
  {code:'V2031029',year:2020,title:'PFPP do CEIP Plurilingüe de Belesar',entity:'Vigo',detail:'Actualización de ferramentas tecnolóxicas para docentes',hours:14,topic:'Competencia dixital'},
  {code:'G1902018',year:2019,title:'A historia, os usos e a aprendizaxe da lingua escrita',entity:'CAFI',detail:'Os REA ao servizo da lingua escrita',hours:1,topic:'REA e coñecemento aberto'},
  {code:'P1921007',year:2019,title:'Emprego da aula virtual como recurso educativo',entity:'Pontevedra',detail:'Sistemas de licenzas Creative Commons',hours:3,topic:'REA e coñecemento aberto'},
  {code:'G1901048',year:2019,title:'Identidade dixital. Elaboración de materiais',entity:'CAFI',detail:'A identidade dixital: creación, desenvolvemento e aplicación de secuencias didácticas',hours:25,topic:'Identidade dixital'},
  {code:'V1802018',year:2018,title:'Formación avanzada no EVA E-Dixgal',entity:'Vigo',detail:'Ferramentas de autor, Recursos Educativos Abertos e licenzas Creative Commons',hours:6,topic:'REA e coñecemento aberto'},
  {code:'V1802023',year:2018,title:'Formación avanzada no EVA E-Dixgal',entity:'Vigo',detail:'Ferramentas de autor nos contornos dixitais',hours:6,topic:'Competencia dixital'},
  {code:'P1801022',year:2018,title:'Formación E-Dixgal para coordinadores',entity:'Pontevedra',detail:'Software libre e licenzas Creative Commons',hours:2,topic:'REA e coñecemento aberto'},
  {code:'G1801059',year:2018,title:'Identidade dixital. Elaboración de materiais',entity:'CAFI',detail:'Identidade dixital. Elaboración de materiais',hours:25,topic:'Identidade dixital'},
  {code:'G1701108',year:2017,title:'Identidade dixital. Elaboración de materiais',entity:'CAFI',detail:'Identidade dixital',hours:25,topic:'Identidade dixital'},
  {code:'V1731101',year:2017,title:'PFPP do CPI Curros Enríquez',entity:'Vigo',detail:'Dinamización da páxina web',hours:9,topic:'Web e aulas virtuais'},
  {code:'G1601033',year:2016,title:'Crear e compartir Recursos Educativos Abertos',entity:'CAFI',detail:'Crear e compartir Recursos Educativos Abertos',hours:25,topic:'REA e coñecemento aberto'},
  {code:'V1631004',year:2016,title:'PFPP do CEP Pedro Caselles Beltrán',entity:'Vigo',detail:'Creación de contidos na rede',hours:4,topic:'Web e aulas virtuais'},
  {code:'S1531013',year:2016,title:'PFPP do IES de Porto do Son',entity:'CAFI',detail:'Solucións tecnolóxicas Abalar',hours:3,topic:'Competencia dixital'},
  {code:'S1505006',year:2016,title:'PFPP: solucións tecnolóxicas Abalar',entity:'CAFI',detail:'Solucións tecnolóxicas Abalar',hours:3,topic:'Competencia dixital'},
  {code:'G1501020',year:2016,title:'Transformación creativa de Recursos Educativos Abertos con eXeLearning',entity:'CAFI',detail:'Coordinación e docencia do curso',hours:50,topic:'REA e coñecemento aberto'},
  {code:'C1431008',year:2015,title:'PFPP do CPI Castro Baxoi',entity:'A Coruña',detail:'Formación vinculada ao PFPP',hours:3,topic:'Competencia dixital'},
  {code:'C1401072',year:2015,title:'PFPP Aulas 2.0: novas metodoloxías e estratexias no ensino a través da web e das redes sociais',entity:'A Coruña',detail:'Formación vinculada ao PFPP',hours:3,topic:'Web e aulas virtuais'},
  {code:'G1401053',year:2015,title:'Transformación creativa de Recursos Educativos Abertos con eXeLearning',entity:'CAFI',detail:'Recursos Educativos Abertos con eXeLearning',hours:50,topic:'REA e coñecemento aberto'},
  {code:'G1402009',year:2015,title:'Xornadas escol@TIC.2015',entity:'CAFI',detail:'Moderación da sala «A formación en TIC. Está á altura?»',hours:1,topic:'Coordinación e formación'},
  {code:'C1306023',year:2014,title:'As TIC como vehículo da nosa bagaxe cultural',entity:'A Coruña',detail:'As TIC',hours:12,topic:'Competencia dixital'},
  {code:'S1306011',year:2014,title:'Compostela nos ollos',entity:'CAFI',detail:'Aula virtual e eXeLearning',hours:9,topic:'Web e aulas virtuais'},
  {code:'X1314001',year:2013,title:'II Congreso de Software Libre de Educación',entity:'Servizos Centrais',detail:'Relatorio no congreso',hours:1,topic:'REA e coñecemento aberto'},
  {code:'G1302004',year:2014,title:'IV Xornadas de formación dos xefes e xefas dos departamentos de orientación',entity:'CAFI',detail:'Viaxando en TIC a través das intelixencias',hours:1,topic:'Competencia dixital'},
  {code:'S1301052',year:2013,title:'Nivel básico inicial en tecnoloxías da información e da comunicación',entity:'CAFI',detail:'Aula TIC, sistemas operativos, PDI, repositorios de contidos, XADE e Meiga',hours:15,topic:'Competencia dixital'},
  {code:'C1307004',year:2014,title:'O contorno Abalar: ferramentas de autor',entity:'A Coruña',detail:'Formación vinculada ao contorno Abalar',hours:12,topic:'Competencia dixital'},
  {code:'C1331027',year:2014,title:'PFPP do CPI Castro Baxoi',entity:'A Coruña',detail:'Formación vinculada ao PFPP',hours:6,topic:'Competencia dixital'},
  {code:'C1305086',year:2014,title:'Os contidos educativos e o coñecemento libre na era Abalar. Estratexias colaborativas',entity:'A Coruña',detail:'Contidos educativos e coñecemento libre',hours:6,topic:'REA e coñecemento aberto'},
  {code:'G1302005',year:2014,title:'Xornadas escol@TIC.2014',entity:'CAFI',detail:'Metodoloxía de traballo na aula usando TIC (moderación)',hours:2,topic:'Coordinación e formación'},
  {code:'P1207003',year:2012,title:'Introdución Abalar',entity:'Pontevedra',detail:'Introdución Abalar',hours:2,topic:'Competencia dixital'},
  {code:'X1201109',year:2013,title:'IV Seminario-obradoiro de avaliación de materiais didácticos. O proxecto Abalar, cara a onde?',entity:'Servizos Centrais',detail:'Participación no seminario-obradoiro',hours:2,topic:'Coordinación e formación'},
  {code:'S1201053',year:2012,title:'Formación técnica nos elementos da aula Abalar',entity:'CAFI',detail:'Presentación do proxecto Abalar, equipamento, redeiras e aula virtual',hours:6,topic:'Competencia dixital'},
  {code:'S1201083',year:2012,title:'Grupo de traballo: preparación de materiais para cursos do itinerario formativo Abalar',entity:'CAFI',detail:'Preparación de materiais formativos',hours:30,topic:'Coordinación e formación'},
  {code:'G1202018',year:2013,title:'I Xornada de coordinadores e coordinadoras do proxecto Abalar',entity:'CAFI',detail:'Infraestrutura técnica e software libre no proxecto Abalar',hours:1,topic:'Competencia dixital'},
  {code:'G1201042',year:2013,title:'Nivel avanzado en tecnoloxías da información e da comunicación',entity:'CAFI',detail:'Nivel avanzado en TIC',hours:25,topic:'Competencia dixital'},
  {code:'G1201043',year:2013,title:'Nivel avanzado en tecnoloxías da información e da comunicación. Edición Abalar',entity:'CAFI',detail:'Coñecemento, utilización e xestión dunha aula Abalar utilizando as TIC',hours:25,topic:'Competencia dixital'},
  {code:'S1207015',year:2013,title:'PFAC Abalar do CEIP A Mahía',entity:'CAFI',detail:'A aula Abalar, funcionamento e recursos educativos',hours:6,topic:'Competencia dixital'},
  {code:'S1231005',year:2013,title:'PFPP do CEIP de Pedrouzos',entity:'CAFI',detail:'Contidos dixitais en web e Moodle',hours:9,topic:'Web e aulas virtuais'},
  {code:'S1201102',year:2013,title:'Contidos dixitais en contorno web e Moodle',entity:'CAFI',detail:'Contidos dixitais en web e Moodle',hours:9,topic:'Web e aulas virtuais'},
  {code:'G1201111',year:2013,title:'Proxecto Abalar: estratexias para a intervención, dinamización e análise por parte da Inspección educativa',entity:'CAFI',detail:'Configuración do equipamento dunha aula Abalar',hours:4,topic:'Competencia dixital'},
  {code:'S1207023',year:2012,title:'Proxecto de formación Abalar do IES Plurilingüe de Ames. Modalidade I',entity:'CAFI',detail:'Experiencia de traballo dun centro Abalar',hours:2,topic:'Competencia dixital'},
  {code:'C1207033',year:2013,title:'Usos e posibilidades das TIC',entity:'A Coruña',detail:'Moodle',hours:8,topic:'Web e aulas virtuais'},
  {code:'P1201067',year:2012,title:'Xestión TIC de contidos nun CMUS',entity:'Pontevedra',detail:'Traballando con licenzas abertas na educación musical',hours:9,topic:'REA e coñecemento aberto'},
  {code:'P1105013',year:2011,title:'Aula virtual: utilización da plataforma Moodle como ferramenta no proceso de ensino-aprendizaxe',entity:'Pontevedra',detail:'Xestión dun curso e coñecementos básicos de Moodle',hours:2,topic:'Web e aulas virtuais'},
  {code:'G1102009',year:2012,title:'Compartindo a práctica educativa das aulas hospitalarias',entity:'CAFI',detail:'Aplicacións do proxecto webs dinámicas nas Aulas Hospitalarias de Galicia',hours:4,topic:'Web e aulas virtuais'},
  {code:'G1102010',year:2012,title:'Congreso: formación e competencias na nova sociedade. Tecnoloxías da información e comunicación',entity:'CAFI',detail:'Software libre no ensino',hours:3,topic:'REA e coñecemento aberto'},
  {code:'X1101408',year:2012,title:'I Congreso de Software Libre para Ciencia, Matemáticas e Tecnoloxía',entity:'Servizos Centrais',detail:'Participación como relator',hours:2,topic:'REA e coñecemento aberto'},
  {code:'P1101012',year:2012,title:'Educar nas emocións na educación infantil',entity:'Pontevedra',detail:'Requisitos de uso dos recursos para traballar a educación emocional',hours:3,topic:'Competencia dixital'},
  {code:'P1101079',year:2011,title:'Estratexias para o asesoramento colaborativo no proxecto Abalar',entity:'Pontevedra',detail:'Sistemas de licenzas Creative Commons',hours:3,topic:'REA e coñecemento aberto'},
  {code:'G1101007',year:2012,title:'Formación a distancia en webs dinámicas para o emprego didáctico nos centros educativos',entity:'CAFI',detail:'Emprego das webs dinámicas nos centros educativos',hours:30,topic:'Formación en liña'},
  {code:'X1101060',year:2011,title:'Formación a distancia en webs dinámicas para o emprego didáctico nos centros educativos. Edición Abalar',entity:'CAFI',detail:'Formación a distancia para o emprego didáctico nos centros',hours:30,topic:'Formación en liña'},
  {code:'V1101035',year:2011,title:'Formación básica nas TIC. Edición Abalar',entity:'Vigo',detail:'Proxecto Abalar: modelo de soporte tecnolóxico. O servidor de centro',hours:3,topic:'Competencia dixital'},
  {code:'F1101031',year:2011,title:'Formación técnica nos elementos da aula Abalar',entity:'Ferrol',detail:'Módulo IV',hours:3,topic:'Competencia dixital'},
  {code:'S1101043',year:2011,title:'Formación técnica nos elementos da aula Abalar',entity:'CAFI',detail:'Servidor de centro Abalar e conectividade',hours:6,topic:'Competencia dixital'},
  {code:'P1101052',year:2011,title:'Formación técnica nos elementos da aula Abalar',entity:'Pontevedra',detail:'Infraestrutura de rede Abalar',hours:6,topic:'Competencia dixital'},
  {code:'C1101049',year:2011,title:'Formación técnica nos elementos da aula Abalar',entity:'A Coruña',detail:'Formación técnica',hours:3,topic:'Competencia dixital'},
  {code:'P1103001',year:2012,title:'III Encontros de coordinadores e coordinadoras de actividades de formación en centros',entity:'Pontevedra',detail:'Coñecemento libre en educación: licenzas Creative Commons',hours:3,topic:'REA e coñecemento aberto'},
  {code:'P1101050',year:2012,title:'Tendencias actuais de aprendizaxe en liña e web 2.0 na área de Tecnoloxía',entity:'Pontevedra',detail:'Licenzas Creative Commons e aprendizaxe en liña. Fase práctica',hours:3,topic:'Formación en liña'},
  {code:'P1007007',year:2010,title:'Dinamización da biblioteca e as TIC',entity:'Pontevedra',detail:'A páxina web: organización e posibilidades',hours:2,topic:'Biblioteca e lingua'},
  {code:'S1001094',year:2010,title:'Fase I. Dinamizadores e dinamizadoras TIC nos centros educativos',entity:'Santiago',detail:'Servidor de CED. Aplicación de xestión de recursos',hours:3,topic:'Competencia dixital'},
  {code:'S1001095',year:2010,title:'Fase I. Dinamizadores e dinamizadoras TIC nos centros educativos',entity:'Santiago',detail:'Elementos Abalar. O servidor de centro',hours:9,topic:'Competencia dixital'},
  {code:'S1005064',year:2011,title:'Ferramentas web 2.0: fomentando a aprendizaxe autónoma e interactiva',entity:'Santiago',detail:'Moodle',hours:6,topic:'Web e aulas virtuais'},
  {code:'S1005001',year:2011,title:'Grupos de traballo',entity:'Santiago',detail:'Participación formativa',hours:6,topic:'Coordinación e formación'},
  {code:'L1001131',year:2011,title:'Introdución a GNU/Linux Ubuntu 10.4 Netbook',entity:'Lugo',detail:'Instalación de GNU/Linux Ubuntu e xestión básica do sistema',hours:10,topic:'Competencia dixital'},
  {code:'L1001022',year:2010,title:'Webs dinámicas para centros educativos. Drupal, Moodle e Coppermine',entity:'Lugo',detail:'Drupal',hours:7,topic:'Web e aulas virtuais'},
  {code:'L1001023',year:2010,title:'Webs dinámicas para centros educativos. Drupal, Moodle e Coppermine',entity:'Lugo',detail:'Drupal',hours:9,topic:'Web e aulas virtuais'},
  {code:'C0905034',year:2009,title:'A nosa web II',entity:'A Coruña',detail:'A nosa web II',hours:8,topic:'Web e aulas virtuais'},
  {code:'S0905063',year:2010,title:'Ferramentas web 2.0: fomentando o traballo colaborativo',entity:'Santiago',detail:'Webs dinámicas',hours:7,topic:'Web e aulas virtuais'},
  {code:'X0904001',year:2010,title:'Formación a distancia en administración das webs dinámicas dos centros educativos',entity:'Servizos Centrais',detail:'Coordinación ou docencia en liña',hours:30,topic:'Formación en liña'},
  {code:'S0901024',year:2009,title:'Formación de dinamizadores e dinamizadoras das tecnoloxías da información e da comunicación en centros educativos',entity:'Santiago',detail:'O software libre no ensino',hours:6,topic:'REA e coñecemento aberto'},
  {code:'S0907002',year:2009,title:'Iniciación ao Moodle',entity:'Santiago',detail:'Contorno virtual de ensino e aprendizaxe',hours:12,topic:'Web e aulas virtuais'},
  {code:'C0905119',year:2009,title:'O portal educativo e a aula virtual do centro: exploración das posibilidades e dimensións na práctica educativa',entity:'A Coruña',detail:'Portal educativo e aula virtual',hours:6,topic:'Web e aulas virtuais'},
  {code:'C0901077',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'A Coruña',detail:'A web 2.0 e a dinamización da lingua: Drupal',hours:3,topic:'Biblioteca e lingua'},
  {code:'F0901055',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Ferrol',detail:'A web 2.0 e a dinamización da lingua: Drupal',hours:3,topic:'Biblioteca e lingua'},
  {code:'S0901059',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Santiago',detail:'A web 2.0 e a dinamización da lingua: Moodle',hours:3,topic:'Biblioteca e lingua'},
  {code:'L0901080',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Lugo',detail:'A web 2.0 e a dinamización da lingua: Moodle',hours:3,topic:'Biblioteca e lingua'},
  {code:'O0901072',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Ourense',detail:'A web 2.0 e a dinamización da lingua',hours:3,topic:'Biblioteca e lingua'},
  {code:'P0901079',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Pontevedra',detail:'A web 2.0 e a dinamización da lingua: Moodle',hours:3,topic:'Biblioteca e lingua'},
  {code:'V0901070',year:2010,title:'V Seminario de dinamización lingüística no ensino',entity:'Vigo',detail:'A web 2.0 e a dinamización da lingua: Moodle',hours:3,topic:'Biblioteca e lingua'},
  {code:'S0805007',year:2008,title:'A apertura do centro ao contorno a través das novas tecnoloxías',entity:'Santiago',detail:'A web dinámica, Drupal',hours:3,topic:'Web e aulas virtuais'},
  {code:'C0805086',year:2009,title:'A nosa web',entity:'A Coruña',detail:'A nosa web',hours:3,topic:'Web e aulas virtuais'},
  {code:'X0804058',year:2009,title:'A web da Axenda 21 Escolar de Galicia',entity:'Servizos Centrais',detail:'A web da Axenda 21 Escolar de Galicia',hours:10,topic:'Web e aulas virtuais'},
  {code:'X0804044',year:2008,title:'A web da Axenda 21 Escolar de Galicia',entity:'Servizos Centrais',detail:'Xestión da web Axenda 21 Escolar de Galicia',hours:10,topic:'Web e aulas virtuais'},
  {code:'S0801039',year:2009,title:'A xestión administrativa e académica da titoría con XADE',entity:'Santiago',detail:'Estrutura e nocións básicas sobre o funcionamento da aplicación',hours:15,topic:'Competencia dixital'},
  {code:'X0804006',year:2009,title:'A xestión administrativa e académica da titoría con XADE. Edición PLATEGA',entity:'Servizos Centrais',detail:'Formación en XADE',hours:15,topic:'Formación en liña'},
  {code:'P0805040',year:2009,title:'Aprendo a aprender a través da páxina web',entity:'Pontevedra',detail:'Aprendo a aprender a través da páxina web',hours:6,topic:'Web e aulas virtuais'},
  {code:'S0805088',year:2009,title:'Creación da páxina web dinámica do centro',entity:'Santiago',detail:'Webs dinámicas: Drupal',hours:3,topic:'Web e aulas virtuais'},
  {code:'S0805087',year:2009,title:'Elaboración da páxina web do centro en Drupal',entity:'Santiago',detail:'Ferramentas para conformar a páxina web dinámica',hours:3,topic:'Web e aulas virtuais'},
  {code:'S0807008',year:2008,title:'Integración das TIC no centro educativo',entity:'Santiago',detail:'Introdución a webs dinámicas: Drupal',hours:6,topic:'Competencia dixital'},
  {code:'C0805073',year:2008,title:'Planificación e xestión da páxina web do centro como espazo comunitario de intercambio de coñecemento',entity:'A Coruña',detail:'Planificación e xestión web',hours:8,topic:'Web e aulas virtuais'},
  {code:'S0805096',year:2009,title:'Plataforma educativa do IES Lamas de Abade: comunidade de aprendizaxe en liña con Moodle e xestión avanzada de galerías con Coppermine',entity:'Santiago',detail:'Técnicas de traballo na plataforma de teleformación Moodle e galerías',hours:4,topic:'Formación en liña'},
  {code:'S0805097',year:2009,title:'Plataforma educativa do IES Lamas de Abade: creación da web dinámica do centro con Drupal',entity:'Santiago',detail:'Xestión da páxina web e introdución a Drupal',hours:4,topic:'Web e aulas virtuais'}
];
